export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const LIKED_PRODUCT = "LIKED_PRODUCT";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
